### ISSUE TITLE
与react比较选哪个

### ISSUE THREAD

**Issue by yinxufeng** [kevingzhang/meteor101cam#1]
最近react很火，如果做移动端开发，理论上react native性能上要比meteor好。那该如何选择呢？
另外期待麦子学院视频教程更新，讲的很棒，讲的很棒，讲的很棒，重要事情说三遍！！！

**Comment by kevingzhang** [comment]
麦子学员当时对更新教程并不很热心. 后来我自己有没有时间继续制作课程了. 偶尔我出差路过中国的时候经常会被热心者拉过去做一些讲座研讨什么的. 也许他们会放一些录像出来. 

React native 距离真正能用还有至少1年的时间. 至少 android 到今天为止还不支持. 

React.js, React Native 和 Meteor 并不是互相替换的关系. 事实上他们并不是同样的东西. 我目前做的项目基本上是 Meteor 来做 full stack, 其中把 Blaze 换成 React.js 的方式. 然后计划明年以后换成 React Native

**Comment by yinxufeng** [comment]
由于我原来是做PC和嵌入式开发的，现在项目需要要接触Web和移动开发，所以技术选型比较困惑。我觉得可以按照您现在的开发方式方式去学习技术栈，Meteor + React.js。不过目前没有这种混合方面的例子，不知道meteor101cam或者其他demo能有reactjs版本。

**Comment by kevingzhang** [comment]
Google 一下 react package meteor

**Comment by yinxufeng** [comment]
thanks
