### ISSUE TITLE
感谢信

### ISSUE THREAD

**Issue by tsq** [kevingzhang/meteor101cam#2]
今天意外看到了您的这篇教程，写得非常棒，通俗易懂，自己也从中收获很多。
提这个issue，只是想表达一下对您的感谢 😄

**Comment by kevingzhang** [comment]
不必感谢, 这些都是很多年以前做的贡献了. 我早以不做前端开发了. 也不用这些技术了. 但是思想和理论是一样的. 学习思想精髓比学习技术更加重要

**Comment by tsq** [comment]
👍 👍 👍
